version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      BACKEND_URL: "http://backend:50051"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork:
