GET http://localhost:8000/health_check HTTP/1.1

###

POST http://localhost:8000/ HTTP/1.1
content-type: application/json

{
    "key": "key1",
    "value": "value1" 
}

###

GET http://localhost:8000/key1 HTTP/1.1