name: Rust

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: install protobuf-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run frontend tests
        run: cargo test -p frontend -- --test-threads=1

      - name: Run backend tests
        run: cargo test -p backend

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: install protobuf-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: install protobuf-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings
